model: gpt-5-mini--minimal
api: openai
max_tokens: 128000
read_cost: 0.25
write_cost: 2
concurrent_requests: 32
temperature: null
top_p: null
human_readable_id: GPT-5-mini (minimal)
batch_processing: false
openai_responses: true
date: "2025-08-07"
reasoning:
  summary: "auto"