default_max_tokens: 64000
default_temperature: 0.6
name: "sycophancy_best_of_n"
prompt_path: "data/prompts/checker.txt" 
data_path: "data/postprocess/sycophancy_best_of_n/test_samples.json"
n_solutions: -1
