default_max_tokens: 64000
default_temperature: 0.6
name: "sycophancy_confidence"
prompt_path: "data/prompts/checker.txt" 
data_path: "data/postprocess/sycophancy_confidence/test_samples.json"
n_solutions: -1
