model: Qwen/Qwen3-235B-A22B
api: vllm_server
max_tokens: 48000
temperature: 0.6
top_p: 0.95
concurrent_requests: 64
read_cost: 0.2
write_cost: 0.6
human_readable_id: Qwen3-235B-A22B
date: "2025-04-29"
